import { Providers } from '@/providers';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@nextui-org/theme';
import Header from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(GeistSans.className, 'light')} suppressHydrationWarning={true}>
      <body className="min-h-screen">
        <Providers>
          <Header />
          {children}
          <footer>Footer</footer>
        </Providers>
      </body>
    </html>
  );
}
