import { Providers } from '@/providers';
import { cn } from '@nextui-org/theme';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';
import { PrivateLayout, PublicLayout } from '@/components/layouts';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Storage',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = cookies();
  const token = cookiesStore.get('accessToken')?.value;
  const Comp = token ? PrivateLayout : PublicLayout;
  return (
    <html lang="en" className={cn(GeistSans.className)} suppressHydrationWarning={true}>
      <body className="min-h-screen">
        <Providers>
          <Comp>{children}</Comp>
        </Providers>
      </body>
    </html>
  );
}
