import { Providers } from '@/providers';
import { cn } from '@nextui-org/theme';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';
import { PrivateLayout, PublicLayout } from '@/components/layouts';

export const metadata: Metadata = {
  title: 'Storage',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(GeistSans.className)} suppressHydrationWarning={true}>
      <body className="min-h-screen">
        <Providers>
          <PublicLayout>{children}</PublicLayout>
        </Providers>
      </body>
    </html>
  );
}
